# Generated by Django 3.2.6 on 2021-08-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20210829_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
