# Generated by Django 3.2.6 on 2021-08-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20210830_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='seat',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
